language: julia

os:
  - linux
  - osx

branches:
  only:
  - master

julia:
  - 1.2
  - 0.6.4

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Coverage");'
  - julia -e 'import LinearAlgebraicRepresentation; cd(dirname(dirname(pathof(LinearAlgebraicRepresentation)))); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Coverage; import LinearAlgebraicRepresentation; cd(dirname(dirname(pathof(LinearAlgebraicRepresentation)))); Codecov.submit(process_folder())'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
